---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.6-alpine

inputs:
  - name: source-code


run:
  path: sh
  args:
    - '-exc'
    - |
        pip install poetry
        cd source-code
        poetry install
        poetry run pytest -m 'not integration'
